
package cn.sh.yeshine.ns1vauservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2016-12-07T16:25:00.507+08:00
 * Generated source version: 2.5.5
 * 
 */
public final class VauServicesPortType_VauServicesHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.yeshine.sh.cn/ns1VauServices/", "VauServices");

    private VauServicesPortType_VauServicesHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VauServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VauServices ss = new VauServices(wsdlURL, SERVICE_NAME);
        VauServicesPortType port = ss.getVauServicesHttpPort();  
        
        {
        System.out.println("Invoking startTranscoding...");
        cn.sh.yeshine.ns1vauservices.StartTranscodingReq _startTranscoding_startTranscodingReq = null;
        cn.sh.yeshine.ns1vauservices.StartTranscodingRes _startTranscoding__return = port.startTranscoding(_startTranscoding_startTranscodingReq);
        System.out.println("startTranscoding.result=" + _startTranscoding__return);


        }
        {
        System.out.println("Invoking upErrorDev...");
        cn.sh.yeshine.ns1vauservices.UpErrorDevReq _upErrorDev_upErrorDevReq = null;
        cn.sh.yeshine.ns1vauservices.UpErrorDevRes _upErrorDev__return = port.upErrorDev(_upErrorDev_upErrorDevReq);
        System.out.println("upErrorDev.result=" + _upErrorDev__return);


        }
        {
        System.out.println("Invoking serverHeartbeat...");
        cn.sh.yeshine.ns1vauservices.ServerHeartbeatReq _serverHeartbeat_serverHeartbeatReq = null;
        cn.sh.yeshine.ns1vauservices.ServerHeartbeatRes _serverHeartbeat__return = port.serverHeartbeat(_serverHeartbeat_serverHeartbeatReq);
        System.out.println("serverHeartbeat.result=" + _serverHeartbeat__return);


        }
        {
        System.out.println("Invoking stopTranscoding...");
        cn.sh.yeshine.ns1vauservices.StopTranscodingReq _stopTranscoding_stopTranscodingReq = null;
        cn.sh.yeshine.ns1vauservices.StopTranscodingRes _stopTranscoding__return = port.stopTranscoding(_stopTranscoding_stopTranscodingReq);
        System.out.println("stopTranscoding.result=" + _stopTranscoding__return);


        }

        System.exit(0);
    }

}
