
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.sh.yeshine.ns1vauservices;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2016-12-07T16:25:00.532+08:00
 * Generated source version: 2.5.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "VauServices",
                      portName = "VauServicesHttpPort",
                      targetNamespace = "http://www.yeshine.sh.cn/ns1VauServices/",
                      endpointInterface = "cn.sh.yeshine.ns1vauservices.VauServicesPortType")
                      
public class VauServicesPortTypeImpl implements VauServicesPortType {

    private static final Logger LOG = Logger.getLogger(VauServicesPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.sh.yeshine.ns1vauservices.VauServicesPortType#startTranscoding(cn.sh.yeshine.ns1vauservices.StartTranscodingReq  startTranscodingReq )*
     */
    public cn.sh.yeshine.ns1vauservices.StartTranscodingRes startTranscoding(StartTranscodingReq startTranscodingReq) { 
        LOG.info("Executing operation startTranscoding");
        System.out.println(startTranscodingReq);
        try {
            cn.sh.yeshine.ns1vauservices.StartTranscodingRes _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.sh.yeshine.ns1vauservices.VauServicesPortType#upErrorDev(cn.sh.yeshine.ns1vauservices.UpErrorDevReq  upErrorDevReq )*
     */
    public cn.sh.yeshine.ns1vauservices.UpErrorDevRes upErrorDev(UpErrorDevReq upErrorDevReq) { 
        LOG.info("Executing operation upErrorDev");
        System.out.println(upErrorDevReq);
        try {
            cn.sh.yeshine.ns1vauservices.UpErrorDevRes _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.sh.yeshine.ns1vauservices.VauServicesPortType#serverHeartbeat(cn.sh.yeshine.ns1vauservices.ServerHeartbeatReq  serverHeartbeatReq )*
     */
    public cn.sh.yeshine.ns1vauservices.ServerHeartbeatRes serverHeartbeat(ServerHeartbeatReq serverHeartbeatReq) { 
        LOG.info("Executing operation serverHeartbeat");
        System.out.println(serverHeartbeatReq);
        try {
            cn.sh.yeshine.ns1vauservices.ServerHeartbeatRes _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.sh.yeshine.ns1vauservices.VauServicesPortType#stopTranscoding(cn.sh.yeshine.ns1vauservices.StopTranscodingReq  stopTranscodingReq )*
     */
    public cn.sh.yeshine.ns1vauservices.StopTranscodingRes stopTranscoding(StopTranscodingReq stopTranscodingReq) { 
        LOG.info("Executing operation stopTranscoding");
        System.out.println(stopTranscodingReq);
        try {
            cn.sh.yeshine.ns1vauservices.StopTranscodingRes _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
