
package cn.sh.yeshine.ns1vauservices;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2016-12-07T16:25:00.568+08:00
 * Generated source version: 2.5.5
 * 
 */
 
public class VauServicesPortType_VauServicesHttpPort_Server{

    protected VauServicesPortType_VauServicesHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new VauServicesPortTypeImpl();
        String address = "http://localhost:8080/vtduservice/services/VauServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new VauServicesPortType_VauServicesHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
