package cn.sh.yeshine.ns1vauservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2016-12-07T16:25:00.571+08:00
 * Generated source version: 2.5.5
 * 
 */
@WebServiceClient(name = "VauServices", 
                  wsdlLocation = "VauService.wsdl",
                  targetNamespace = "http://www.yeshine.sh.cn/ns1VauServices/") 
public class VauServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.yeshine.sh.cn/ns1VauServices/", "VauServices");
    public final static QName VauServicesHttpPort = new QName("http://www.yeshine.sh.cn/ns1VauServices/", "VauServicesHttpPort");
    static {
        URL url = VauServices.class.getResource("VauService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(VauServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "VauService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public VauServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VauServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VauServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VauServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VauServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VauServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns VauServicesPortType
     */
    @WebEndpoint(name = "VauServicesHttpPort")
    public VauServicesPortType getVauServicesHttpPort() {
        return super.getPort(VauServicesHttpPort, VauServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VauServicesPortType
     */
    @WebEndpoint(name = "VauServicesHttpPort")
    public VauServicesPortType getVauServicesHttpPort(WebServiceFeature... features) {
        return super.getPort(VauServicesHttpPort, VauServicesPortType.class, features);
    }

}
