
package cn.sh.sttri.ns1recordservices;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2016-03-18T13:46:43.287+08:00
 * Generated source version: 2.5.5
 * 
 */
 
public class RecordServicesPortType_RecordServicesHttpPort_Server{

    protected RecordServicesPortType_RecordServicesHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new RecordServicesPortTypeImpl();
        String address = "http://127.0.0.1:8081/RecordServices/services/RecordServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new RecordServicesPortType_RecordServicesHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
