
package cn.sh.sttri.ns1recordservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2016-03-18T13:46:43.242+08:00
 * Generated source version: 2.5.5
 * 
 */
public final class RecordServicesPortType_RecordServicesHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.sttri.sh.cn/ns1RecordServices/", "RecordServices");

    private RecordServicesPortType_RecordServicesHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecordServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecordServices ss = new RecordServices(wsdlURL, SERVICE_NAME);
        RecordServicesPortType port = ss.getRecordServicesHttpPort();  
        
        {
        System.out.println("Invoking devEndRecord...");
        cn.sh.sttri.ns1recordservices.DevEndRecordReq _devEndRecord_devEndRecordReq = null;
        cn.sh.sttri.ns1recordservices.DevEndRecordRes _devEndRecord__return = port.devEndRecord(_devEndRecord_devEndRecordReq);
        System.out.println("devEndRecord.result=" + _devEndRecord__return);


        }
        {
        System.out.println("Invoking devStreamError...");
        cn.sh.sttri.ns1recordservices.DevStreamErrorReq _devStreamError_devStreamErrorReq = null;
        cn.sh.sttri.ns1recordservices.DevStreamErrorRes _devStreamError__return = port.devStreamError(_devStreamError_devStreamErrorReq);
        System.out.println("devStreamError.result=" + _devStreamError__return);


        }
        {
        System.out.println("Invoking devRecordUp...");
        cn.sh.sttri.ns1recordservices.DevRecordUpReq _devRecordUp_devRecordUpReq = null;
        cn.sh.sttri.ns1recordservices.DevRecordUpRes _devRecordUp__return = port.devRecordUp(_devRecordUp_devRecordUpReq);
        System.out.println("devRecordUp.result=" + _devRecordUp__return);


        }
        {
        System.out.println("Invoking devStartRecord...");
        cn.sh.sttri.ns1recordservices.DevStartRecordReq _devStartRecord_devStartRecordReq = null;
        cn.sh.sttri.ns1recordservices.DevStartRecordRes _devStartRecord__return = port.devStartRecord(_devStartRecord_devStartRecordReq);
        System.out.println("devStartRecord.result=" + _devStartRecord__return);


        }

        System.exit(0);
    }

}
