package cn.sh.sttri.ns1recordservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2016-03-18T13:46:43.290+08:00
 * Generated source version: 2.5.5
 * 
 */
@WebServiceClient(name = "RecordServices", 
                  wsdlLocation = "RecordService.wsdl",
                  targetNamespace = "http://www.sttri.sh.cn/ns1RecordServices/") 
public class RecordServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sttri.sh.cn/ns1RecordServices/", "RecordServices");
    public final static QName RecordServicesHttpPort = new QName("http://www.sttri.sh.cn/ns1RecordServices/", "RecordServicesHttpPort");
    static {
        URL url = RecordServices.class.getResource("RecordService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RecordServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "RecordService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public RecordServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RecordServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecordServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecordServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RecordServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RecordServicesPortType
     */
    @WebEndpoint(name = "RecordServicesHttpPort")
    public RecordServicesPortType getRecordServicesHttpPort() {
        return super.getPort(RecordServicesHttpPort, RecordServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordServicesPortType
     */
    @WebEndpoint(name = "RecordServicesHttpPort")
    public RecordServicesPortType getRecordServicesHttpPort(WebServiceFeature... features) {
        return super.getPort(RecordServicesHttpPort, RecordServicesPortType.class, features);
    }

}
