
package cn.sh.sttri.ns1hlsliveservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2015-12-15T09:57:39.715+08:00
 * Generated source version: 2.5.5
 * 
 */
public final class HlsliveServicesPortType_HlsliveServicesHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.sttri.sh.cn/ns1HlsliveServices/", "HlsliveServices");

    private HlsliveServicesPortType_HlsliveServicesHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HlsliveServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HlsliveServices ss = new HlsliveServices(wsdlURL, SERVICE_NAME);
        HlsliveServicesPortType port = ss.getHlsliveServicesHttpPort();  
        
        {
        System.out.println("Invoking stopRtspToHls...");
        cn.sh.sttri.ns1hlsliveservices.StopRtspToHlsReq _stopRtspToHls_stopRtspToHlsReq = null;
        cn.sh.sttri.ns1hlsliveservices.StopRtspToHlsRes _stopRtspToHls__return = port.stopRtspToHls(_stopRtspToHls_stopRtspToHlsReq);
        System.out.println("stopRtspToHls.result=" + _stopRtspToHls__return);


        }
        {
        System.out.println("Invoking startRtspToHls...");
        cn.sh.sttri.ns1hlsliveservices.StartRtspToHlsReq _startRtspToHls_startRtspToHlsReq = null;
        cn.sh.sttri.ns1hlsliveservices.StartRtspToHlsRes _startRtspToHls__return = port.startRtspToHls(_startRtspToHls_startRtspToHlsReq);
        System.out.println("startRtspToHls.result=" + _startRtspToHls__return);


        }

        System.exit(0);
    }

}
