package cn.sh.sttri.ns1hlsliveservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2015-12-15T09:57:39.772+08:00
 * Generated source version: 2.5.5
 * 
 */
@WebServiceClient(name = "HlsliveServices", 
                  wsdlLocation = "HlsliveService.wsdl",
                  targetNamespace = "http://www.sttri.sh.cn/ns1HlsliveServices/") 
public class HlsliveServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sttri.sh.cn/ns1HlsliveServices/", "HlsliveServices");
    public final static QName HlsliveServicesHttpPort = new QName("http://www.sttri.sh.cn/ns1HlsliveServices/", "HlsliveServicesHttpPort");
    static {
        URL url = HlsliveServices.class.getResource("HlsliveService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(HlsliveServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "HlsliveService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public HlsliveServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HlsliveServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HlsliveServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HlsliveServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HlsliveServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HlsliveServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HlsliveServicesPortType
     */
    @WebEndpoint(name = "HlsliveServicesHttpPort")
    public HlsliveServicesPortType getHlsliveServicesHttpPort() {
        return super.getPort(HlsliveServicesHttpPort, HlsliveServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HlsliveServicesPortType
     */
    @WebEndpoint(name = "HlsliveServicesHttpPort")
    public HlsliveServicesPortType getHlsliveServicesHttpPort(WebServiceFeature... features) {
        return super.getPort(HlsliveServicesHttpPort, HlsliveServicesPortType.class, features);
    }

}
