package cn.sh.sttri.ns1hlsliveservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.5
 * 2015-12-15T09:57:39.760+08:00
 * Generated source version: 2.5.5
 * 
 */
@WebService(targetNamespace = "http://www.sttri.sh.cn/ns1HlsliveServices/", name = "HlsliveServicesPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HlsliveServicesPortType {

    @WebResult(name = "stopRtspToHlsRes", targetNamespace = "http://www.sttri.sh.cn/ns1HlsliveServices/", partName = "stopRtspToHlsRes")
    @WebMethod
    public StopRtspToHlsRes stopRtspToHls(
        @WebParam(partName = "stopRtspToHlsReq", name = "stopRtspToHlsReq", targetNamespace = "http://www.sttri.sh.cn/ns1HlsliveServices/")
        StopRtspToHlsReq stopRtspToHlsReq
    );

    @WebResult(name = "startRtspToHlsRes", targetNamespace = "http://www.sttri.sh.cn/ns1HlsliveServices/", partName = "startRtspToHlsRes")
    @WebMethod
    public StartRtspToHlsRes startRtspToHls(
        @WebParam(partName = "startRtspToHlsReq", name = "startRtspToHlsReq", targetNamespace = "http://www.sttri.sh.cn/ns1HlsliveServices/")
        StartRtspToHlsReq startRtspToHlsReq
    );
}
